name: Markdown lint

on:
  push:
    paths:
      - '**.md'
  pull_request:

jobs:
  lint:

    name: Lint Markdown files
    runs-on: ubuntu-20.04

    steps:

      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@v3.4.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown lint (markdownlint-cli)
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
