name: Markdown lint

on:
  push:
    paths:
      - '**.md'
  pull_request:

jobs:
  pre_job:

    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:

      - id: skip_check
        name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  lint:

    name: Lint Markdown files
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown lint (markdownlint-cli)
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
